name = "Bincrypter"
uuid = "96fd710b-316a-421d-b5a6-3410d6b9b0d0"
version = "0.0.1"
authors = ["imohag9 <souidi.hamza90@gmail.com> and contributors"]

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
julia = "1.11"
